data:
  train: "/home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/Active_Continual_Learning/data/QLK15D/train_data_raw.pkl"
  validation: "/home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/Active_Continual_Learning/data/QLK15D/valid_data_raw.pkl"
  test: "/home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/Active_Continual_Learning/data/QLK15D/test_data_raw.pkl"
  pool: "/home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/Active_Continual_Learning/data/QLK15D/pool_data_raw.pkl"
save_paths:
  plots: "/home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/Active_Continual_Learning/plots/"
  outputs: "/home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/Active_Continual_Learning/outputs/"




#fluxes:  [ "efiitg_gb", "efeitg_gb_div_efiitg_gb","pfiitg_gb_div_efiitg_gb","pfeitg_gb_div_efiitg_gb","vfiitg_gb_div_efiitg_gb"] # 
fluxes: ["efiitg_gb"]
                                    